// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  firebase:{
    apiKey: "AIzaSyAf094upARTulksJojFJtoGf-8rXpfeBjk",
    authDomain: "alpha5-e3638.firebaseapp.com",
    databaseURL: "https://alpha5-e3638.firebaseio.com",
    projectId: "alpha5-e3638",
    storageBucket: "alpha5-e3638.appspot.com",
    messagingSenderId: "5800362524"
  }
};
